sudo: required

language: java

jdk: openjdk8

services:
  - docker

# safelist
branches:
   only:
     - master
install: 
    - git clone https://github.com/Galithil/NGI-RNAseq.git /tmp/NGI-RNAseq
    - git checkout amazon
    - cd /tmp/NGI-RNAseq/tests

#script: "./nextflow run SciLifeLab/NGI-RNAseq -profile docker_test --reads '/tmp/ngi-rna_test_set/*.fastq.gz'"
script: "./docker_test_hisat.sh"
